apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todo-scale
spec:
  minReplicas: 1
  maxRelicas: 5
  metrics:
    - resource:
      name: cpu
      target: 
        averageUtilization: 75
        type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-management